name: CI

on: push

jobs:
  build:
    name: 'Install packages'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install

  checks:
    name: 'Run Checks'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    needs: [build]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Build project'
        run: pnpm run build
        env:
          API_KEY: api_key

      - name: 'Run linter'
        run: pnpm run lint

      - name: 'Run check'
        run: pnpm run check
        env:
          API_KEY: api_key
