name: CI

on: push

env:
  node-version: 20
  pnpm-version: 8

jobs:
  build:
    name: 'Install packages'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up pnpm ${{ env.pnpm-version }}'
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - name: 'Use Node.js ${{ env.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install

  checks:
    name: 'Run Checks'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up pnpm ${{ env.pnpm-version }}'
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - name: 'Use Node.js ${{ env.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Build project'
        run: pnpm run build
        env:
          API_KEY: api_key

      - name: 'Run linter'
        run: pnpm run lint

      - name: 'Run check'
        run: pnpm run check
        env:
          API_KEY: api_key
